---
- name: Patch RHEL Servers
  hosts: all

  roles:
    - shadowman_patching

  tasks:

  
    - name: upgrade all packages (yum)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == "yum"
      register: patchingresult
  
    - name: upgrade all packages (dnf)
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == "dnf"
      register: patchingresultdnf
  

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux_patch
        apply:
          delegate_to: node1
          run_once: true
